### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ThatBooze**
I hate 3. Fuck 3, 4 is better.

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
can we handle 4?

**Comment by ThatBooze** [comment]
¯\\_(ツ)_/¯

**Comment by DBTDerpbox** [comment]
i dont thin k werea rready

**Comment by ThatBooze** [comment]
cat-nonsense

**Comment by S-N00B-1** [comment]
I concur with one of these opinions

**Comment by ThatBooze** [comment]
Okay, how about 🎱 ?

**Comment by DBTDerpbox** [comment]
too late

**Comment by ThatBooze** [comment]
It's never too late.

**Comment by S-N00B-1** [comment]
> too late

too l🎱

**Pull request closed without merging**
